export { default as Header } from './Header';
// export { default as Main } from './main';
export { default as Product } from './Products';
export { default as Footer } from './Footer';
export { default as Categories } from './Categories';
export { default as Workshop } from './Workshop';
export { default as Discount } from './Discount';
export { default as Products } from './Products';
export { default as Facebook } from './Facebook';
export { default as Services } from './Services';
